# Generated by Django 3.0.6 on 2020-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_aiuser_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiuser',
            name='firstName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aiuser',
            name='lastName',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
